### ISSUE TITLE
머지시 코드리뷰 여부

### ISSUE THREAD

**Issue by LuticaCANARD** [KNUT-webstudygroup/KNUT_webchat_frontend#2]
# 주제
- 중요 브런치간 머지시 코드리뷰를 해야할까요?
(* 여기서 말하는 코드리뷰: github에 있는 pull request를 통해서 코드를 확인하고 main에 받을때 심사하게하는 일련의 과정을 의미합니다..)
# 세부주제
- 중요 브런치를 어떻게 정의할 까요?
> 저는 배포를 담당하는 master, 개발한걸 모아둔 develop에 merge를 시도할 때만 코드리뷰를 하게 하는게 맞다고 봅니다...
- 코드리뷰시 한명만 봐도 충분할까요?
> 사실 팀원 적어서 괜찮지 않을까 싶어요...

# 참조
#1

**Comment by okxooxoo** [comment]
준영님 의견에 동의합니다 :)

**Comment by Minkyu01** [comment]
저도 준영님 의견에 동의합니다~! 근데 코드리뷰는 스터디 목적이면 둘다 보는게 좋지 않을까요?

**Comment by LuticaCANARD** [comment]
@Minkyu01 
확실히 스터디라는 면에서 둘 다 보고 머지시키는 방향도 나쁘지 않을것 같아요! 그러면 저희 정책은 develop 브런치에 커밋하기 전에는 두명의 코드리뷰를 거치고 진행하는것으로 하도록 할게요!

**Comment by LuticaCANARD** [comment]
설정 마쳤어요! 의견 고마워요!
